apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitops-cert-level-2-examples
  annotations:
    github.com/project-slug: kevorojas/gitops-cert-level-2-examples
spec:
  type: other
  lifecycle: unknown
  owner: gtm
